# Generated by Django 5.2.6 on 2025-09-29 18:55

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: A01, B12, etc.', max_length=10, unique=True, verbose_name='Código da Vaga')),
                ('status', models.CharField(choices=[('L', 'Livre'), ('O', 'Ocupada'), ('M', 'Em Manutenção')], default='L', max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': [django.db.models.functions.text.Upper('codigo')],
            },
        ),
    ]
