# Generated by Django 5.2.6 on 2025-10-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('livre', 'Livre'), ('ocupada', 'Ocupada'), ('manutencao', 'Em Manutenção')], default='L', max_length=10, verbose_name='Status'),
        ),
    ]
