# Generated by Django 5.2.6 on 2025-10-23 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0001_initial'),
        ('pagamentos', '0002_alter_pagamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='estadia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='estadias.estadia'),
        ),
    ]
