# Generated by Django 5.2.6 on 2025-10-11 17:23

import django.db.models.functions.text
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Ciclano da silva', help_text='Nome completo', max_length=50, verbose_name='Nome')),
                ('fone', models.CharField(default='000000000000', help_text='Número de telefone (Apenas números)', max_length=12, unique=True, verbose_name='Fone')),
                ('email', models.EmailField(default='naoinformado@email.com', help_text='E-mail', max_length=100, unique=True, verbose_name='E-mail')),
                ('endereco', models.CharField(default='naoinformado', help_text='Endereço completo', max_length=300, verbose_name='Endereço')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='pessoas', variations={}, verbose_name='Foto')),
                ('data_nascimento', models.DateField(blank=True, help_text='Data de nascimento', null=True, verbose_name='Data de nascimento')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF ')),
                ('funcao', models.CharField(help_text='Função na empresa', max_length=35, verbose_name='Função')),
                ('data_admissao', models.DateField(help_text='Data de admissão na empresa', verbose_name='Admissão')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': [django.db.models.functions.text.Upper('nome')],
            },
        ),
    ]
