# Generated by Django 5.2.6 on 2025-10-01 12:42

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.pessoa')),
                ('cpf', models.CharField(blank=True, help_text='Digite o CPF', max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, help_text='Data de nascimento', null=True, verbose_name='Data de nascimento')),
                ('funcao', models.CharField(help_text='Função na empresa', max_length=35, verbose_name='Função')),
                ('data_admissao', models.DateField(help_text='Data de admissão na empresa', verbose_name='Admissão')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': [django.db.models.functions.text.Upper('nome')],
            },
            bases=('clientes.pessoa',),
        ),
    ]
