# Generated by Django 5.2.6 on 2025-09-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(help_text='CPF na empresa', max_length=11, verbose_name='clientes.PessoaFisica'),
        ),
    ]
