# Generated by Django 5.2.6 on 2025-11-17 16:19

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='static/pessoas', variations={}, verbose_name='Foto'),
        ),
    ]
