# Generated by Django 5.2.6 on 2025-10-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(blank=True, help_text='Digite o CPF', max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
