# Generated by Django 5.2.6 on 2025-09-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.DecimalField(decimal_places=0, help_text='Digite o CPF', max_digits=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(help_text='Data de admissão na empresa', verbose_name='Admissão'),
        ),
    ]
