# Generated by Django 5.2.6 on 2025-09-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_alter_funcionario_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Digite o CPF', max_digits=11, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
