# Generated by Django 5.2.6 on 2025-09-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(blank=True, help_text='Digite o CPF', max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
