# Generated by Django 5.2.6 on 2025-10-07 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estadias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Calculado')),
                ('metodo', models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX')], max_length=20, null=True, verbose_name='Método de Pagamento')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora do Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=10, verbose_name='Status')),
                ('estada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='estadias.estadia')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
