# Generated by Django 5.2.6 on 2025-10-13 19:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estadias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoAvulso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão')], default='Cartão', max_length=20, verbose_name='Método')),
                ('valor_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Bruto (sem descontos)')),
                ('desconto_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Desconto Aplicado')),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Final (a pagar)')),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('estadia', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pagamento_avulso', to='estadias.estadia')),
            ],
            options={
                'verbose_name': 'Pagamento Avulso',
                'verbose_name_plural': 'Pagamentos Avulsos',
            },
        ),
    ]
