# Generated by Django 5.2.6 on 2025-10-14 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos_avulso', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PagamentoAvulso',
        ),
    ]
