# Generated by Django 5.2.6 on 2025-10-07 17:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0003_alter_estadia_cliente_alter_estadia_data_chegada_and_more'),
        ('pagamentos_avulso', '0002_pagamentoavulso_delete_pagamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamentoavulso',
            options={},
        ),
        migrations.AlterField(
            model_name='pagamentoavulso',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagamentoavulso',
            name='desconto_aplicado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Desconto Aplicado'),
        ),
        migrations.AlterField(
            model_name='pagamentoavulso',
            name='estadia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pagamento_avulso', to='estadias.estadia'),
        ),
        migrations.AlterField(
            model_name='pagamentoavulso',
            name='metodo',
            field=models.CharField(choices=[('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão')], default='CARTAO', max_length=20, verbose_name='Método'),
        ),
        migrations.AlterField(
            model_name='pagamentoavulso',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pagamentoavulso',
            name='valor_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Bruto'),
        ),
        migrations.AlterField(
            model_name='pagamentoavulso',
            name='valor_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Final'),
        ),
    ]
