# Generated by Django 5.2.6 on 2025-10-07 18:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0003_alter_estadia_cliente_alter_estadia_data_chegada_and_more'),
        ('pagamentos_avulso', '0003_alter_pagamentoavulso_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamentoavulso',
            options={'verbose_name': 'Pagamento Avulso', 'verbose_name_plural': 'Pagamentos Avulsos'},
        ),
        migrations.AlterField(
            model_name='pagamentoavulso',
            name='data_pagamento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pagamentoavulso',
            name='desconto_aplicado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Desconto Aplicado'),
        ),
        migrations.AlterField(
            model_name='pagamentoavulso',
            name='estadia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento_avulso', to='estadias.estadia'),
        ),
        migrations.AlterField(
            model_name='pagamentoavulso',
            name='metodo',
            field=models.CharField(choices=[('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão')], default='Cartão', max_length=20, verbose_name='Método'),
        ),
        migrations.AlterField(
            model_name='pagamentoavulso',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pagamentoavulso',
            name='valor_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Bruto (sem descontos)'),
        ),
        migrations.AlterField(
            model_name='pagamentoavulso',
            name='valor_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Final (a pagar)'),
        ),
    ]
