# Generated by Django 5.2.6 on 2025-10-07 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0003_alter_estadia_cliente_alter_estadia_data_chegada_and_more'),
        ('pagamentos_avulso', '0004_alter_pagamentoavulso_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentoavulso',
            name='estadia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pagamento_avulso', to='estadias.estadia'),
        ),
    ]
