# Generated by Django 5.2.6 on 2025-09-20 16:00

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Placa do veiculo', max_length=8, unique=True, verbose_name='Placa')),
                ('marca', models.CharField(help_text='Marca do veiculo', max_length=15, verbose_name='Marca')),
                ('modelo', models.CharField(help_text='Modelo do veiculo', max_length=15, verbose_name='Modelo')),
                ('cor', models.CharField(help_text='Cor do veiculo', max_length=15, verbose_name='Cor')),
                ('qtd_rodas', models.DecimalField(decimal_places=0, help_text='Quantidade de rodas do veículo', max_digits=2, verbose_name='Quantidade de rodas')),
            ],
            options={
                'verbose_name': 'Veiculo',
                'verbose_name_plural': 'Veiculos',
                'ordering': [django.db.models.functions.text.Upper('placa')],
            },
        ),
    ]
