# Generated by Django 5.2.6 on 2025-10-01 12:42

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True, verbose_name='Placa')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('cor', models.CharField(max_length=30, verbose_name='Cor')),
                ('qtd_rodas', models.IntegerField(choices=[(2, '2 rodas'), (3, '3 rodas'), (4, '4 rodas ou mais')], verbose_name='Quantidade de Rodas')),
                ('plano', models.CharField(choices=[('diaria', 'Diária'), ('horario_avulso', 'Horário Avulso'), ('mensal', 'Mensal')], max_length=20, verbose_name='Plano')),
                ('clientes', models.ManyToManyField(related_name='veiculos', to='clientes.clientegeral', verbose_name='Proprietário(s)')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': [django.db.models.functions.text.Upper('placa')],
            },
        ),
    ]
