# Generated by Django 5.2.6 on 2025-10-13 19:47

import django.db.models.deletion
import django.db.models.functions.text
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('valores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True, verbose_name='Placa')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('cor', models.CharField(max_length=30, verbose_name='Cor')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='carros', variations={}, verbose_name='Foto')),
                ('categoria_cnh', models.CharField(choices=[('A', 'A - Motocicleta'), ('B', 'B - Carro'), ('C', 'C - Caminhão'), ('D', 'D - Ônibus/Van'), ('E', 'E - Veículos com reboque'), ('O', 'Outro tipo de categorias')], help_text='Selecione a categorias correspondente ao porte do veículo', max_length=5, verbose_name='Categoria do Veículo')),
                ('clientes', models.ManyToManyField(related_name='veiculos', to='clientes.clientegeral', verbose_name='Proprietário(s)')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valores.plano', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': [django.db.models.functions.text.Upper('placa')],
            },
        ),
    ]
