# Generated by Django 5.2.6 on 2025-09-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_clientepf_clientepj_delete_cliente'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='cliente',
            field=models.ManyToManyField(help_text='Nome do cliente', related_name='cliente', to='clientes.clientepj', verbose_name='Cliente PF'),
        ),
    ]
