# Generated by Django 5.2.6 on 2025-10-22 19:12

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('valores', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': [django.db.models.functions.text.Upper('placa')], 'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='plano_pago',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cliente',
            field=models.ManyToManyField(related_name='veiculos', to='clientes.clientegeral', verbose_name='Clientes'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='categoria_cnh',
            field=models.ForeignKey(limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valores.categoria', verbose_name='Categoria do Veículo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='data_vencimento_plano',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento do Plano'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valores.plano', verbose_name='Plano'),
        ),
    ]
