# Generated by Django 5.2.6 on 2025-10-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='plano',
            field=models.CharField(choices=[('Diaria', 'Diária'), ('Avulso', 'Horário Avulso'), ('Semanal', 'Semanal'), ('Mensal', 'Mensal')], max_length=20, verbose_name='Plano'),
        ),
    ]
