# Generated by Django 5.2.6 on 2025-09-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['placa']},
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='cliente_pf',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='cliente_pj',
        ),
    ]
