# Generated by Django 5.2.6 on 2025-10-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='categoria_cnh',
            field=models.CharField(choices=[('A', 'A - Motocicleta'), ('B', 'B - Carro'), ('C', 'C - Caminhão'), ('D', 'D - Ônibus/Van'), ('E', 'E - Veículos com reboque'), ('O', 'Outro tipo de categorias')], default='A', help_text='Selecione a categorias correspondente ao porte do veículo', max_length=5, verbose_name='Categoria do Veículo'),
        ),
    ]
