# Generated by Django 5.2.6 on 2025-10-22 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_alter_veiculo_options_remove_veiculo_plano_pago_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='cliente',
            new_name='clientes',
        ),
    ]
