# Generated by Django 5.2.6 on 2025-10-02 03:22

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_veiculo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='carros', variations={}, verbose_name='Foto'),
        ),
    ]
