# Generated by Django 5.2.6 on 2025-10-13 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valores', '0003_rename_categoria_categoria_cnh'),
        ('veiculos', '0002_alter_veiculo_categoria_cnh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='categoria_cnh',
            field=models.ForeignKey(limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valores.categoria', verbose_name='Categoria do Veículo'),
        ),
    ]
