# Generated by Django 5.2.6 on 2025-09-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_veiculo_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='object_id',
        ),
    ]
