# Generated by Django 5.2.6 on 2025-09-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('veiculos', '0003_remove_veiculo_content_type_remove_veiculo_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='cliente',
            field=models.ManyToManyField(to='clientes.clientepf'),
        ),
    ]
