# Generated by Django 5.2.6 on 2025-11-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_rename_cliente_veiculo_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/veiculos', verbose_name='Foto'),
        ),
    ]
