# Generated by Django 5.2.6 on 2025-10-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(blank=True, choices=[('Diaria', 'Diária'), ('Avulso', 'Horário Avulso'), ('Semanal', 'Semanal'), ('Mensal', 'Mensal')], max_length=20, null=True, verbose_name='Plano')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('qtd_rodas', models.IntegerField(choices=[(2, '2 rodas'), (3, '3 rodas'), (4, '4 rodas ou mais')], verbose_name='Quantidade de Rodas')),
            ],
            options={
                'verbose_name': 'Valor',
                'verbose_name_plural': 'Valores',
                'permissions': (('alterar_valores', 'Permite atualizar os valores da tabela'),),
            },
        ),
    ]
