# Generated by Django 5.2.6 on 2025-10-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnh', models.CharField(choices=[('A', 'A - Motocicleta'), ('B', 'B - Carro'), ('C', 'C - Caminhão'), ('D', 'D - Ônibus/Van'), ('E', 'E - Veículos com reboque'), ('O', 'Outro tipo de categoria')], default='A', max_length=5, unique=True, verbose_name='Categoria de CNH')),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor adicional pela categoria (%)')),
                ('status', models.BooleanField(default=True, help_text='Marque para ativar a categoria', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Desconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Desconto para funcionário', max_length=100, verbose_name='Nome do desconto')),
                ('tipo', models.CharField(choices=[('PERCENTUAL', 'Percentual (%)'), ('FIXO', 'Valor Fixo (R$)')], default='PERCENTUAL', max_length=20, verbose_name='Tipo de desconto')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Desconto máximo de 100% ou de R$100', max_digits=8, verbose_name='Valor do desconto')),
                ('descricao', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descrição')),
                ('status', models.BooleanField(default=True, help_text='Marque para ativar este desconto', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Desconto',
                'verbose_name_plural': 'Descontos',
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: ', max_length=100, verbose_name='Nome do adicional')),
                ('tipo', models.CharField(choices=[('PERCENTUAL', 'Percentual (%)'), ('FIXO', 'Valor Fixo (R$)')], default='PERCENTUAL', max_length=20, verbose_name='Tipo do adicional')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Somente números', max_digits=8, verbose_name='Valor a adicionar (R$)')),
                ('descricao', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descrição')),
                ('status', models.BooleanField(default=True, help_text='Marque para ativar este valor extra', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Valor Extra',
                'verbose_name_plural': 'Valores Extras',
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Avulso', 'Horário Avulso'), ('Diaria', 'Diaria'), ('Semanal', 'Semanal'), ('Mensal', 'Mensal'), ('Personalizado', 'Personalizado')], default='Avulso', max_length=50, unique=True, verbose_name='Nome do Plano')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Base (R$)')),
                ('status', models.BooleanField(default=True, help_text='Marque para ativar o plano', verbose_name='Ativo')),
                ('descricao', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descrição')),
                ('dias_validade', models.PositiveIntegerField(default=0, help_text='Número de dias de validade (apenas para planos personalizados)', verbose_name='Dias de Validade')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
    ]
