# Generated by Django 5.2.6 on 2025-10-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Desconto para funcionário', max_length=100, verbose_name='Nome do desconto')),
                ('tipo', models.CharField(choices=[('PERCENTUAL', 'Percentual (%)'), ('FIXO', 'Valor Fixo (R$)')], max_length=20, verbose_name='Tipo de desconto')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Somente números', max_digits=8, verbose_name='Valor do desconto')),
                ('ativo', models.BooleanField(default=True, help_text='Marque para ativar este desconto', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Desconto',
                'verbose_name_plural': 'Descontos',
            },
        ),
        migrations.CreateModel(
            name='TabelaDePrecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Preço por hora para carros', max_length=100, verbose_name='Descrição')),
                ('plano', models.CharField(blank=True, choices=[('Diaria', 'Diária'), ('Avulso', 'Horário Avulso'), ('Semanal', 'Semanal'), ('Mensal', 'Mensal')], max_length=20, null=True, verbose_name='Plano')),
                ('qtd_rodas', models.IntegerField(choices=[(2, '2 rodas'), (3, '3 rodas'), (4, '4 rodas ou mais')], verbose_name='Tipo de Veículo (rodas)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Base (R$)')),
            ],
            options={
                'verbose_name': 'Preço da tabela',
                'verbose_name_plural': 'Tabela de Preços',
            },
        ),
        migrations.DeleteModel(
            name='Valores',
        ),
    ]
