# Generated by Django 5.2.6 on 2025-10-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desconto',
            name='codigo_interno',
            field=models.CharField(blank=True, help_text='Identificador único para regras do sistema', max_length=50, null=True, unique=True, verbose_name='Código Interno'),
        ),
    ]
