# Generated by Django 5.2.6 on 2025-10-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categorias',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='status',
            field=models.BooleanField(default=True, help_text='Marque para ativar a categoria', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor adicional pela categoria (%)'),
        ),
    ]
