# Generated by Django 5.2.6 on 2025-10-13 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valores', '0002_rename_categorias_categoria_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='cnh',
        ),
    ]
