# Generated by Django 5.2.6 on 2025-10-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valores', '0002_desconto_tabeladeprecos_delete_valores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: ', max_length=100, verbose_name='Nome do adicional')),
                ('tipo', models.CharField(choices=[('PERCENTUAL', 'Percentual (%)'), ('FIXO', 'Valor Fixo (R$)')], max_length=20, verbose_name='Tipo do adicional')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Somente números', max_digits=8, verbose_name='Valor a adicionar (R$)')),
                ('ativo', models.BooleanField(default=True, help_text='Marque para ativar este valor extra', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Valor Extra',
                'verbose_name_plural': 'Valores Extras',
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(blank=True, choices=[('Diaria', 'Diária'), ('Avulso', 'Horário Avulso'), ('Semanal', 'Semanal'), ('Mensal', 'Mensal')], max_length=20, null=True, verbose_name='Plano')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Base (R$)')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.DeleteModel(
            name='TabelaDePrecos',
        ),
    ]
