# Generated by Django 5.2.6 on 2025-10-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valores', '0003_extra_plano_delete_tabeladeprecos'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Marque para ativar o plano', verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='plano',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('desativado', 'Desativado')], default='ativo', max_length=10, verbose_name='Status'),
        ),
    ]
