# Generated by Django 5.2.6 on 2025-10-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valores', '0003_rename_categoria_categoria_cnh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cnh',
            field=models.CharField(choices=[('A', 'A - Motocicleta'), ('B', 'B - Carro'), ('C', 'C - Caminhão'), ('D', 'D - Ônibus/Van'), ('E', 'E - Veículos com reboque'), ('O', 'Outro tipo de categoria')], default='A', max_length=5, unique=True, verbose_name='Categoria de CNH'),
        ),
    ]
