# Generated by Django 5.2.6 on 2025-10-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valores', '0004_plano_ativo_plano_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='ativo',
        ),
        migrations.AlterField(
            model_name='plano',
            name='status',
            field=models.BooleanField(default=True, help_text='Marque para ativar o plano', verbose_name='Ativo'),
        ),
    ]
