# Generated by Django 5.2.6 on 2025-10-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valores', '0005_alter_plano_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='nome',
            field=models.CharField(choices=[('Avulso', 'Horário Avulso'), ('Diaria', 'Diaria'), ('Semanal', 'Semanal'), ('Mensal', 'Mensal'), ('Outro', 'Outro plano')], default='Avulso', max_length=50, unique=True, verbose_name='Nome do Plano'),
        ),
    ]
