# Generated by Django 5.2.6 on 2025-10-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valores', '0005_remove_plano_ativo_alter_plano_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desconto',
            old_name='ativo',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='extra',
            old_name='ativo',
            new_name='status',
        ),
    ]
