# Generated by Django 5.2.6 on 2025-10-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valores', '0006_rename_ativo_desconto_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desconto',
            name='descricao',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='extra',
            name='descricao',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='plano',
            name='descricao',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='desconto',
            name='tipo',
            field=models.CharField(choices=[('PERCENTUAL', 'Percentual (%)'), ('FIXO', 'Valor Fixo (R$)')], default='PERCENTUAL', max_length=20, verbose_name='Tipo de desconto'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='tipo',
            field=models.CharField(choices=[('PERCENTUAL', 'Percentual (%)'), ('FIXO', 'Valor Fixo (R$)')], default='PERCENTUAL', max_length=20, verbose_name='Tipo do adicional'),
        ),
    ]
