# Generated by Django 5.2.6 on 2025-10-03 18:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modalidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoModalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX')], max_length=20, verbose_name='Método')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='modalidades.modalidade')),
            ],
            options={
                'verbose_name': 'Pagamento de Plano',
                'verbose_name_plural': 'Pagamentos de Planos',
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
