# Generated by Django 5.2.6 on 2025-10-07 15:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0003_alter_estadia_cliente_alter_estadia_data_chegada_and_more'),
        ('pagamentos_modal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano_contratado', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], max_length=10, verbose_name='Plano Contratado')),
                ('metodo', models.CharField(choices=[('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão')], max_length=20, verbose_name='Método de Pagamento')),
                ('valor_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Bruto (sem descontos)')),
                ('desconto_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Desconto Aplicado')),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Final (a pagar)')),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('estadia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento_modal', to='estadias.estadia')),
            ],
            options={
                'verbose_name': 'Pagamento por Modalidade',
                'verbose_name_plural': 'Pagamentos por Modalidade',
            },
        ),
        migrations.DeleteModel(
            name='PagamentoModalidade',
        ),
    ]
