# Generated by Django 5.2.6 on 2025-10-07 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0003_alter_estadia_cliente_alter_estadia_data_chegada_and_more'),
        ('pagamentos_modal', '0002_pagamentomodal_delete_pagamentomodalidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamentomodal',
            options={'verbose_name': 'Pagamento de Modalidade', 'verbose_name_plural': 'Pagamentos de Modalidades'},
        ),
        migrations.AddField(
            model_name='pagamentomodal',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pagamentomodal',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamentomodal',
            name='estadia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pagamento_modal', to='estadias.estadia'),
        ),
        migrations.AlterField(
            model_name='pagamentomodal',
            name='plano_contratado',
            field=models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], max_length=20, verbose_name='Plano Contratado'),
        ),
        migrations.AlterField(
            model_name='pagamentomodal',
            name='valor_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Bruto'),
        ),
        migrations.AlterField(
            model_name='pagamentomodal',
            name='valor_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Final'),
        ),
    ]
