# Generated by Django 5.2.6 on 2025-09-29 20:43

import django.db.models.deletion
import django.db.models.functions.text
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=50, verbose_name='Nome')),
                ('fone', models.CharField(help_text='Numero de telefone', max_length=15, verbose_name='Fone')),
                ('email', models.EmailField(help_text='E-mail', max_length=100, unique=True, verbose_name='E-mail')),
                ('endereco', models.CharField(help_text='Endereço completo', max_length=300, verbose_name='Endereço')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='pessoas', variations={}, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': [django.db.models.functions.text.Upper('nome')],
            },
        ),
        migrations.CreateModel(
            name='ClientePF',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.pessoa')),
                ('cpf', models.CharField(blank=True, help_text='Digite o CPF', max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, help_text='Data de nascimento', null=True, verbose_name='Data de nascimento')),
                ('plano', models.CharField(choices=[('diaria', 'Diária'), ('horario_avulso', 'Horário Avulso'), ('mensal', 'Mensal')], max_length=20, verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Cliente PF',
                'verbose_name_plural': 'Clientes PF',
                'ordering': [django.db.models.functions.text.Upper('nome')],
            },
            bases=('clientes.pessoa',),
        ),
        migrations.CreateModel(
            name='ClientePJ',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.pessoa')),
                ('empresa', models.CharField(help_text='Nome da empresa', max_length=100, verbose_name='Empresa')),
                ('cnpj', models.DecimalField(decimal_places=0, help_text='Digite o CNPJ da empresa', max_digits=14, unique=True, verbose_name='CNPJ')),
                ('plano', models.CharField(choices=[('diaria', 'Diária'), ('horario_avulso', 'Horário Avulso'), ('mensal', 'Mensal')], max_length=20, verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Cliente PJ',
                'verbose_name_plural': 'Clientes PJ',
                'ordering': [django.db.models.functions.text.Upper('nome')],
            },
            bases=('clientes.pessoa',),
        ),
    ]
