# Generated by Django 5.2.6 on 2025-10-06 22:08

import django.db.models.deletion
import django.db.models.functions.text
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=50, verbose_name='Nome')),
                ('fone', models.CharField(help_text='Número de telefone (Apenas números)', max_length=15, unique=True, verbose_name='Fone')),
                ('email', models.EmailField(help_text='E-mail', max_length=100, unique=True, verbose_name='E-mail')),
                ('endereco', models.CharField(help_text='Endereço completo', max_length=300, verbose_name='Endereço')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='pessoas', variations={}, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': [django.db.models.functions.text.Upper('nome')],
            },
        ),
        migrations.CreateModel(
            name='ClienteGeral',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.pessoa')),
                ('tipo_cliente', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, verbose_name='Tipo de Cliente')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF (Apenas números)')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ (Apenas números)')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': [django.db.models.functions.text.Upper('nome'), django.db.models.functions.text.Upper('empresa')],
            },
            bases=('clientes.pessoa',),
        ),
    ]
