# Generated by Django 5.2.6 on 2025-10-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='fone',
            field=models.CharField(help_text='Número de telefone (Apenas números)', max_length=12, unique=True, verbose_name='Fone'),
        ),
    ]
