# Generated by Django 5.2.6 on 2025-09-18 17:30

import django.db.models.functions.text
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=50, verbose_name='Nome')),
                ('fone', models.CharField(help_text='Numero de telefone', max_length=15, verbose_name='Fone')),
                ('email', models.EmailField(help_text='E-mail', max_length=100, unique=True, verbose_name='E-mail')),
                ('endereco', models.CharField(help_text='Endereço completo', max_length=300, verbose_name='Endereço')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='pessoas', variations={}, verbose_name='Foto')),
                ('cpf', models.DecimalField(decimal_places=0, help_text='Digite o CPF', max_digits=11, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, help_text='Data de nascimento', null=True, verbose_name='Data de nascimento')),
                ('num_cadastro', models.DecimalField(decimal_places=0, help_text='Numero de cadastro da empresa', max_digits=5, verbose_name='N° cadastro')),
                ('plano', models.CharField(help_text='Tipo do plano da empresa', max_length=15, verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': [django.db.models.functions.text.Upper('nome')],
            },
        ),
        migrations.DeleteModel(
            name='ClientePF',
        ),
        migrations.DeleteModel(
            name='ClientePJ',
        ),
    ]
