# Generated by Django 5.2.6 on 2025-10-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientegeral',
            name='email',
            field=models.EmailField(help_text='E-mail', max_length=100, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='clientegeral',
            name='endereco',
            field=models.CharField(help_text='Endereço completo', max_length=300, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='clientegeral',
            name='fone',
            field=models.CharField(help_text='Número de telefone (Apenas números)', max_length=12, unique=True, verbose_name='Fone'),
        ),
        migrations.AlterField(
            model_name='clientegeral',
            name='nome',
            field=models.CharField(help_text='Nome completo', max_length=50, verbose_name='Nome'),
        ),
    ]
