# Generated by Django 5.2.6 on 2025-09-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_delete_clientepf_delete_clientepj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='num_cadastro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='plano',
        ),
    ]
