# Generated by Django 5.2.6 on 2025-09-18 17:59

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_cliente_num_cadastro_remove_cliente_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Digite o CNPJ da empresa', max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2, verbose_name='Tipo de Pessoa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, help_text='Digite o CPF', max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fone',
            field=models.CharField(help_text='Número de telefone', max_length=15, verbose_name='Fone'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='clientes', variations={}, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(help_text='Nome ou Razão Social', max_length=100, verbose_name='Nome'),
        ),
    ]
