# Generated by Django 5.2.6 on 2025-10-11 17:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('funcionarios', '0001_initial'),
        ('vagas', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(blank=True, choices=[('Diaria', 'Diária'), ('Avulso', 'Horário Avulso'), ('Semanal', 'Semanal'), ('Mensal', 'Mensal')], max_length=20, null=True, verbose_name='Plano')),
                ('data_chegada', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.clientegeral')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario')),
                ('vaga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vagas.vaga')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veiculos.veiculo')),
            ],
            options={
                'verbose_name': 'Estadia',
                'verbose_name_plural': 'Estadias',
                'ordering': ['-data_chegada'],
                'permissions': (('encerrar_estadia', 'Permite fazer o encerramento de uma estadia'),),
            },
        ),
    ]
