# Generated by Django 5.2.6 on 2025-10-01 17:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('funcionarios', '0001_initial'),
        ('vagas', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_chegada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora da Chegada')),
                ('data_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora da Saída')),
                ('finalizada', models.BooleanField(default=False, verbose_name='Finalizada')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Total')),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente responsável pela estada.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.clientegeral', verbose_name='Cliente')),
                ('funcionario', models.ForeignKey(blank=True, help_text='Funcionário que registrou a entrada.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario', verbose_name='Funcionário Responsável')),
                ('vaga', models.ForeignKey(help_text='Vaga ocupada pelo veículo.', on_delete=django.db.models.deletion.PROTECT, to='vagas.vaga', verbose_name='Vaga')),
                ('veiculo', models.ForeignKey(help_text='Veículo que está estacionando.', on_delete=django.db.models.deletion.PROTECT, to='veiculos.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Estada',
                'verbose_name_plural': 'Estadas',
                'ordering': ['-data_chegada'],
            },
        ),
    ]
