# Generated by Django 5.2.6 on 2025-10-07 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadia',
            options={'ordering': ['-data_chegada'], 'permissions': (('encerrar_estadia', 'Permite fazer o encerramento de uma estadia'),), 'verbose_name': 'Estadia', 'verbose_name_plural': 'Estadias'},
        ),
    ]
