# Generated by Django 5.2.6 on 2025-10-07 15:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_pessoa_fone'),
        ('estadias', '0001_initial'),
        ('funcionarios', '0002_alter_funcionario_cpf'),
        ('vagas', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadia',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.clientegeral', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='data_chegada',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Chegada'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Saída'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='finalizada',
            field=models.BooleanField(default=False, verbose_name='Finalizada'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='vaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vagas.vaga', verbose_name='Vaga'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veiculos.veiculo', verbose_name='Veículo'),
        ),
    ]
