# Generated by Django 5.2.6 on 2025-10-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('estadias', '0001_initial'),
        ('funcionarios', '0001_initial'),
        ('vagas', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estada',
            new_name='Estadia',
        ),
        migrations.AlterModelOptions(
            name='estadia',
            options={'ordering': ['-data_chegada'], 'verbose_name': 'Estadia', 'verbose_name_plural': 'Estadias'},
        ),
    ]
