# Generated by Django 5.2.6 on 2025-10-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadia',
            name='valor_total',
        ),
    ]
