# Generated by Django 5.2.6 on 2025-10-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0002_remove_estadia_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadia',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Valor Total'),
        ),
    ]
