# Generated by Django 5.2.6 on 2025-10-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0002_alter_estadia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadia',
            name='plano',
            field=models.CharField(blank=True, choices=[('Diaria', 'Diária'), ('Avulso', 'Horário Avulso'), ('Semanal', 'Semanal'), ('Mensal', 'Mensal')], max_length=20, null=True, verbose_name='Plano'),
        ),
    ]
