# Generated by Django 5.2.6 on 2025-10-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0003_alter_estadia_cliente_alter_estadia_data_chegada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadia',
            name='plano',
            field=models.CharField(blank=True, choices=[('diaria', 'Diária'), ('horario_avulso', 'Horário Avulso'), ('mensal', 'Mensal')], max_length=20, null=True, verbose_name='Plano'),
        ),
    ]
