# Generated by Django 5.2.6 on 2025-10-03 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0004_estadia_plano'),
        ('vagas', '0002_alter_vaga_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadia',
            name='vaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vagas.vaga'),
        ),
    ]
