# Generated by Django 5.2.6 on 2025-10-13 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_pagamento', models.DateTimeField(blank=True, null=True)),
                ('valido_ate', models.DateTimeField(blank=True, null=True)),
                ('veiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modalidade', to='veiculos.veiculo')),
            ],
            options={
                'verbose_name': 'Modalidade de Plano',
                'verbose_name_plural': 'Modalidades de Planos',
            },
        ),
    ]
